Allow an `override` matrix to reduce CI workload.
If `matrix.yaml` contains a non-empty job matrix names `override`, this will be used instead of the `pull_request` matrix. The PR branch protections will prevent the branch from being merged as long as an override exists.

diff --git a/.github/actions/workflow-results/action.yml b/.github/actions/workflow-results/action.yml
--- a/.github/actions/workflow-results/action.yml
+++ b/.github/actions/workflow-results/action.yml
@@ -88,9 +88,17 @@ runs:
       id: check-dispatch
       shell: bash --noprofile --norc -euo pipefail {0}
       run: |
-        if "${GITHUB_ACTION_PATH}/verify-job-success.py" workflow/job_ids.json; then
-          echo "success=true" >> "${GITHUB_OUTPUT}"
-        else
+        if ! "${GITHUB_ACTION_PATH}/verify-job-success.py" workflow/job_ids.json; then
           echo "success=false" >> "${GITHUB_OUTPUT}"
           exit 1
         fi
+
+        if [ -f workflow/override.json ]; then
+          echo "::notice::Workflow matrix was overridden. Failing jobs."
+          echo "Override matrix:"
+          cat workflow/override.json | jq -c '.'
+          echo "success=false" >> "${GITHUB_OUTPUT}"
+          exit 1
+        fi
+
+        echo "success=true" >> "${GITHUB_OUTPUT}"
