WIP.
[skip-vdc][skip-matx][skip-docs]

diff --git a/.github/actions/workflow-results/action.yml b/.github/actions/workflow-results/action.yml
--- a/.github/actions/workflow-results/action.yml
+++ b/.github/actions/workflow-results/action.yml
@@ -124,8 +124,10 @@ runs:
       continue-on-error: true
       shell: bash --noprofile --norc -euo pipefail {0}
       run: |
+        echo "::group::Failure Logs"
         python3 "${GITHUB_ACTION_PATH}/parse-failure-logs.py" \
-          workflow/workflow.json results/jobs.json jobs > workflow/failure_summary.md || :
+          workflow/workflow.json results/jobs.json jobs | tee workflow/failure_summary.md || :
+        echo "::endgroup::"
 
     - name: Prepare final summary
       id: final-summary
@@ -142,7 +144,7 @@ runs:
         readonly success=${{ steps.check-jobs.outputs.success }}
         readonly icon=$(if ${success}; then echo "🥳"; else echo "😬"; fi)
         (
-          echo "## [${icon} Job Matrix Results]($(cat workflow/summary_url.txt))"
+          echo "# [${icon} Job Matrix Results]($(cat workflow/summary_url.txt))"
           declare -a files=(
             workflow/final_summary.md
             workflow/failure_summary.md
@@ -167,6 +169,15 @@ runs:
           echo "### $(cat execution/heading.txt)"
           echo ""
           echo "See results [here]($(cat workflow/summary_url.txt))."
+          if [[ -s workflow/errors_list.md ]]; then
+            echo ""
+            echo "<details><summary>Errors</summary>"
+            echo ""
+            # Prefix each row with a list dash
+            sed 's/^/- /' workflow/errors_list.md
+            echo ""
+            echo "</details>"
+          fi
         ) | tee pr_comment.md
         echo "::endgroup::"
 
