Explicitly check exit code from script.

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -50,7 +50,11 @@ jobs:
       - name: Run build script
         run: | 
             sccache -s > sccache_before.txt
-            time ./${{ inputs.build_script }} "${{inputs.compiler_exe}}" "${{inputs.std}}" "${{inputs.gpu_build_archs}}"
+            cmd="./${{ inputs.build_script }} \"${{inputs.compiler_exe}}\" \"${{inputs.std}}\" \"${{inputs.gpu_build_archs}}\""
+            eval $cmd || exit_code=$?
+            if [ ! -z "$exit_code" ]; then
+                echo "::error::Command '$cmd' failed with exit code $exit_code"
+            fi
             sccache -s > sccache_after.txt
       - name: Calculate sccache hit rate
         run: |
@@ -60,7 +64,7 @@ jobs:
         if: ${{ failure() }}
         run: |
           echo "::notice::To reproduce this build locally, run the following commands:" 
-          echo "git clone --branch $(echo $GITHUB_REF | cut -d'/' -f3) --single-branch https://github.com/$GITHUB_REPOSITORY.git && cd $(echo $GITHUB_REPOSITORY | cut -d'/' -f2) && git checkout $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
+          echo "git clone --branch $(echo $GITHUB_REF | cut -d'/' -f3) --single-branch https://github.com/$GITHUB_REPOSITORY.git && cd $(echo $GITHUB_REPOSITORY | cut -d'/' -f2) && git checkout $GITHUB_SHA"
   test:
     needs: build
     if:  ${{ !cancelled() && ( needs.build.result == 'success' || needs.build.result == 'skipped' ) && inputs.test_script != '' && inputs.test_image != '' }}
