update build-rapids.yml to use launch.sh

diff --git a/.github/workflows/build-rapids.yml b/.github/workflows/build-rapids.yml
--- a/.github/workflows/build-rapids.yml
+++ b/.github/workflows/build-rapids.yml
@@ -24,88 +24,145 @@ jobs:
     name: Build RAPIDS (${{ matrix.libs }})
     if: needs.check-event.outputs.ok == 'true'
     needs: check-event
-    secrets: inherit
-    # TODO: This workflow contains vendored changes from rapidsai/shared-workflows.
-    # This can use rapidsai/shared-workflows if those changes are upstreamed.
-    uses: ./.github/workflows/build-in-devcontainer.yml
-    # uses: rapidsai/shared-workflows/.github/workflows/build-in-devcontainer.yaml@branch-24.06
+    runs-on: ${{ fromJSON(github.repository != 'NVIDIA/cccl' && '"ubuntu-latest"' || '"linux-amd64-cpu32"') }}
     strategy:
       fail-fast: false
       matrix:
         include:
-          - { libs: 'rmm KvikIO cudf cudf_kafka cuspatial',        }
-          - { libs: 'rmm ucxx raft cuvs',                          }
-          - { libs: 'rmm ucxx raft cumlprims_mg cuml',             }
-          - { libs: 'rmm ucxx raft cugraph-ops wholegraph cugraph' }
+          - { cuda: '12.2', libs: 'rmm KvikIO cudf cudf_kafka cuspatial',        }
+          - { cuda: '12.2', libs: 'rmm ucxx raft cuvs',                          }
+          - { cuda: '12.2', libs: 'rmm ucxx raft cumlprims_mg cuml',             }
+          - { cuda: '12.2', libs: 'rmm ucxx raft cugraph-ops wholegraph cugraph' }
     permissions:
-      actions: read
-      packages: read
       id-token: write
       contents: read
-      pull-requests: read
-    with:
-      dir: 'ci/rapids'
-      arch: '["amd64"]'
-      cuda: '["12.2"]'
-      pkgr: '["conda"]'
-      node_type: cpu32
-      extra-repo-deploy-key: RAPIDSAI_CUMLPRIMS_DEPLOY_KEY
-      extra-repo-deploy-key-2: RAPIDSAI_CUGRAPH_OPS_DEPLOY_KEY
-      env: |
-        CI=true
-        RAPIDS_LIBS=${{ matrix.libs }}
-      # Uncomment one of these to customize the git repo and branch for a RAPIDS lib:
-      #   RAPIDS_cmake_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cudf_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cudf_kafka_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cugraph_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cugraph_ops_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cuml_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cumlprims_mg_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cuspatial_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_cuvs_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_KvikIO_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_raft_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_rmm_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      #   RAPIDS_ucxx_GIT_REPO={"upstream": "rapidsai", "tag": "branch-0.39"}
-      #   RAPIDS_wholegraph_GIT_REPO={"upstream": "rapidsai", "tag": "branch-24.08"}
-      build_command: |
-        declare -a failures
-        declare -A failures_map
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+      - name: Add NVCC problem matcher
+        run: echo "::add-matcher::$(pwd)/.github/problem-matchers/problem-matcher.json"
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-NVIDIA
+          aws-region: us-east-2
+          role-duration-seconds: 43200 # 12h
+      - name: Run command # Do not change this step's name, it is checked in parse-job-times.py
+        env:
+          CI: true
+          RAPIDS_LIBS: ${{ matrix.libs }}
+          # Uncomment any of these to customize the git repo and branch for a RAPIDS lib:
+          # RAPIDS_cmake_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cudf_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cudf_kafka_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cugraph_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cugraph_ops_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cuml_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cumlprims_mg_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cuspatial_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_cuvs_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_KvikIO_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_raft_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_rmm_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+          # RAPIDS_ucxx_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-0.39"}'
+          # RAPIDS_wholegraph_GIT_REPO: '{"upstream": "rapidsai", "tag": "branch-24.08"}'
+        run: |
+          set -x;
+          echo "[host] user: $(whoami)"
+          echo "[host]  UID: $(id -u)"
+          echo "[host]  GID: $(id -g)"
+          stat ~/.aws || true
+          stat ~/.aws/config || true
+          stat ~/.aws/credentials || true
 
-        # Configure and build each lib with -DBUILD_TESTS=OFF, then again with -DBUILD_TESTS=ON
-        for RAPIDS_ENABLE_TESTS in OFF ON; do
-          ~/cccl/ci/rapids/post-create-command.sh
-          for lib in ${{ matrix.libs }}; do
-            sccache -z
-            if ! configure-${lib}-cpp || ! build-${lib}-cpp; then
-              if ! test -v failures_map["${lib}"]; then
-                failures+=("${lib}")
-                failures_map["${lib}"]=1
+          cat <<"EOF" > "$RUNNER_TEMP/ci-entrypoint.sh"
+          #! /usr/bin/env bash
+          # Start the ssh-agent and add the repo deploy keys
+          if ! pgrep ssh-agent >/dev/null 2>&1; then eval "$(ssh-agent -s)"; fi
+          ssh-add - <<< '${{ secrets.RAPIDSAI_CUMLPRIMS_DEPLOY_KEY }}'
+          ssh-add - <<< '${{ secrets.RAPIDSAI_CUGRAPH_OPS_DEPLOY_KEY }}'
+          devcontainer-utils-init-ssh-deploy-keys || true
+          exec "$@"
+          EOF
+
+          cat <<"EOF" > "$RUNNER_TEMP/ci.sh"
+          #! /usr/bin/env bash
+          set -eo pipefail
+
+          . ~/cccl/ci/rapids/post-create-command.sh;
+
+          declare -a failures
+          declare -A failures_map
+
+          # Configure and build each lib with -DBUILD_TESTS=OFF, then again with -DBUILD_TESTS=ON
+          for RAPIDS_ENABLE_TESTS in OFF ON; do
+            _apply_manifest_modifications;
+            for lib in ${RAPIDS_LIBS}; do
+              sccache -z
+              if ! configure-${lib}-cpp || ! build-${lib}-cpp; then
+                if ! test -v failures_map["${lib}"]; then
+                  failures+=("${lib}")
+                  failures_map["${lib}"]=1
+                fi
               fi
-            fi
-            sccache --show-adv-stats
+              sccache --show-adv-stats
+            done
           done
-        done
 
-        # Print failures and exit
-        if test ${#failures[@]} -gt 0; then
-          echo "::error:: Failures: ${failures[*]}"
-          echo -e "::group::️❗ \e[1;31mInstructions to Reproduce CI Failure Locally\e[0m"
-          echo "::error:: To replicate this failure locally, follow the steps below:"
-          echo "1. Clone the repository, and navigate to the correct branch and commit:"
-          echo "   git clone --branch $GITHUB_REF_NAME --single-branch https://github.com/$GITHUB_REPOSITORY.git && cd $(echo $GITHUB_REPOSITORY | cut -d'/' -f2) && git checkout $GITHUB_SHA"
-          echo ""
-          echo "2. Run the failed command inside the same Docker container used by this CI job:"
-          cat <<__EOF
+          # Print failures and exit
+          if test ${#failures[@]} -gt 0; then
+            echo "::error:: Failures: ${failures[*]}"
+            echo -e "::group::️❗ \e[1;31mInstructions to Reproduce CI Failure Locally\e[0m"
+            echo "::error:: To replicate this failure locally, follow the steps below:"
+            echo "1. Clone the repository, and navigate to the correct branch and commit:"
+            echo "   git clone --branch $GITHUB_REF_NAME --single-branch https://github.com/$GITHUB_REPOSITORY.git && cd $(echo $GITHUB_REPOSITORY | cut -d'/' -f2) && git checkout $GITHUB_SHA"
+            echo ""
+            echo "2. Run the failed command inside the same Docker container used by this CI job:"
+            cat <<__EOF
              RAPIDS_LIBS='${RAPIDS_LIBS}' \\
           $(for lib in cmake ${RAPIDS_LIBS}; do var=RAPIDS_${lib//-/_}_GIT_REPO; echo "   $var='${!var}' \\"; done)
-             .devcontainer/launch.sh -d -c 12.2 -H rapids-conda -- ./ci/rapids/rapids-entrypoint.sh \\
-             /bin/bash -li -c 'uninstall-all -j -qqq && clean-all -j && build-all -j -v || exec /bin/bash -li'
-        __EOF
-          echo ""
-          echo "For additional information, see:"
-          echo "   - DevContainer Documentation: https://github.com/NVIDIA/cccl/blob/main/.devcontainer/README.md"
-          echo "   - Continuous Integration (CI) Overview: https://github.com/NVIDIA/cccl/blob/main/ci-overview.md"
-          exit 1
-        fi
+               .devcontainer/launch.sh -d -c ${{matrix.cuda}} -H rapids-conda -- ./ci/rapids/rapids-entrypoint.sh \\
+               /bin/bash -li -c 'uninstall-all -j -qqq && clean-all -j && build-all -j -v || exec /bin/bash -li'
+          __EOF
+            echo ""
+            echo "For additional information, see:"
+            echo "   - DevContainer Documentation: https://github.com/NVIDIA/cccl/blob/main/.devcontainer/README.md"
+            echo "   - Continuous Integration (CI) Overview: https://github.com/NVIDIA/cccl/blob/main/ci-overview.md"
+            exit 1
+          fi
+          EOF
+
+          chmod +x "$RUNNER_TEMP"/ci{,-entrypoint}.sh
+
+          mkdir -p "$RUNNER_TEMP/.aws"
+
+          cat <<EOF > "$RUNNER_TEMP/.aws/config"
+          [default]
+          bucket=rapids-sccache-devs
+          region=us-east-2
+          EOF
+
+          cat <<EOF > "$RUNNER_TEMP/.aws/credentials"
+          [default]
+          aws_access_key_id=$AWS_ACCESS_KEY_ID
+          aws_session_token=$AWS_SESSION_TOKEN
+          aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
+          EOF
+
+          chmod 0600 "$RUNNER_TEMP/.aws/credentials"
+          chmod 0664 "$RUNNER_TEMP/.aws/config"
+
+          .devcontainer/launch.sh \
+            --docker \
+            --cuda ${{matrix.cuda}} \
+            --host rapids-conda \
+            --env VAULT_HOST= \
+            --env "GITHUB_SHA=$GITHUB_SHA" \
+            --env "GITHUB_REF_NAME=$GITHUB_REF_NAME" \
+            --env "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" \
+            --volume "$RUNNER_TEMP/ci.sh:/ci.sh" \
+            --volume "$RUNNER_TEMP/.aws:/home/coder/.aws" \
+            --volume "$RUNNER_TEMP/ci-entrypoint.sh:/ci-entrypoint.sh" \
+            -- /ci-entrypoint.sh ./ci/rapids/rapids-entrypoint.sh /ci.sh
