[skip-tests] Move verify-devcontainer to reusable workflow.

diff --git a/.github/workflows/verify-devcontainers.yml b/.github/workflows/verify-devcontainers.yml
--- a/.github/workflows/verify-devcontainers.yml
+++ b/.github/workflows/verify-devcontainers.yml
@@ -1,10 +1,7 @@
-
 name: Verify devcontainers
 
 on:
-  push:
-    branches:
-      - "pull-request/[0-9]+"
+  workflow_call:
 
 defaults:
   run:
@@ -15,7 +12,33 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  verify-make-devcontainers:
+    name: Verify devcontainer files are up-to-date
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+    - name: Setup jq and yq
+      run: |
+        sudo apt-get update
+        sudo apt-get install jq -y
+        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64
+        sudo chmod +x /usr/local/bin/yq
+    - name: Run the script to generate devcontainer files
+      run: |
+        ./.devcontainer/make_devcontainers.sh --verbose
+    - name: Check for changes
+      run: |
+        if [[ $(git diff --stat) != '' ]]; then
+          git diff --minimal
+          echo "::error:: Dev Container files are out of date. Run the .devcontainer/make_devcontainers.sh script and commit the changes."
+          exit 1
+        else
+          echo "Dev Container files are up-to-date."
+        fi
+
   get-devcontainer-list:
+    needs: verify-make-devcontainers
     name: Get list of devcontainer.json files
     runs-on: ubuntu-latest
     outputs:
